export enum DMConversactionState {
    WAITING_USER_TO_CONFIRM_MARKED_PAYMENT = 1,
    WAITING_USER_TO_PROVIDE_ACCOUNT_NAME = 2,
    WAITING_USER_TO_PROVIDE_RECEIPT_IMAGE = 3,
    WAITING_ADMIN_TO_APPROVE_PAYMENT = 4,
    CLOSED = 5
}