export enum PaypointComponentActionsEnum {
    SELECT_PRODUCTS,
    CHOOSE_CASUAL_PAYMENT_METHOD,
    CHOOSE_INTEGRATED_PAYMENT_METHOD,
    MARK_PAYMENT_AS_SENT,
    PAYMENT_REQUEST_FORM_SUBMITED,
    PAYMENT_REQUEST_CANCELLED,

    MARK_INCOMING_PAYMENT_AS_SUCCESS,
    MARK_INCOMING_PAYMENT_AS_FAILED,
    MARK_INCOMING_PAYMENT_AS_FAKE

}