export enum PaypointComponentActionsEnum {
    SELECT_PRODUCTS,
    CHOOSE_CASUAL_PAYMENT_METHOD,
    CHOOSE_INTEGRATED_PAYMENT_METHOD,
    MARK_PAYMENT_AS_SENT,
    CONFIRM_MARKED_PAYMENT,
    DENY_MARKED_PAYMENT
}